import uuid

from datetime import datetime

from sqlalchemy import (
    Boolean, 
    DateTime, 
    ForeignKey, 
    String
)
from sqlalchemy.orm import (
    Mapped, 
    mapped_column, 
    relationship
)

from app.core.enums import OrgRole
from app.db.base import (
    Base, 
    TimestampMixin, 
    UUIDMixin
)


class User(Base, UUIDMixin, TimestampMixin):
    """
    Represents an authenticated user account tied to a specific Organization.

    This model stores core application profile data, audit tracking metrics,
    and maps directly back to the Supabase Auth user entity via 'supabase_uid'.
    """
    __tablename__ = "users"

    # The unique identifier generated by Supabase Auth (auth.users.id).
    # Used to seamlessly map incoming Supabase tokens to our local database context.
    supabase_uid: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)

    # Primary contact and identity email address.
    # Indexed for rapid login verification and unique checks.
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False, index=True)

    # The user's full display name (e.g., "Madhav Chandok").
    full_name: Mapped[str] = mapped_column(String(255), nullable=False)

    # Foreign key referencing the organization this user belongs to.
    # ON DELETE CASCADE ensures that if an organization is deleted, all associated 
    # users are scrubbed automatically to avoid dangling data.
    org_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # The access role assigned to the user within their organization context.
    # Stored as a string representation of the OrgRole enum (e.g., 'owner', 'admin', 'member').
    org_role: Mapped[OrgRole] = mapped_column(String(20), default=OrgRole.MEMBER.value, nullable=False)

    # Administrative flag indicating if the account is allowed to log in and interact with resources.
    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)

    # --- Security Auditing Fields ---
    
    # Tracks the exact timestamp of the user's last successful authentication.
    # Timezone-aware to align with the database's global auditing schema.
    last_login_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Records the IP address used during the last login session.
    # Helpful for threat detection, geographic anomaly checks, and session validation.
    last_login_ip: Mapped[str | None] = mapped_column(String(100), nullable=True)

    # Relationships
    # Many-to-One: Many users belong to a single organization.
    # Uses 'selectin' loading to efficiently fetch the tenant layout in async pipelines without N+1 overhead.
    organization = relationship(
        "Organization",
        foreign_keys=lambda: User.org_id,
        back_populates="users",
        lazy="selectin",
    )
