"""fixed ambiguous foreign keys between user and organizations.

Revision ID: 27fd40fc9690
Revises: 4e7cabe9b185
Create Date: 2026-05-16 15:59:45.772880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27fd40fc9690'
down_revision: Union[str, Sequence[str], None] = '4e7cabe9b185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
