"""fix ambiguous foreign keys between user and organizations.

Revision ID: 4e7cabe9b185
Revises: 0004be5e009a
Create Date: 2026-05-16 15:55:39.329226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e7cabe9b185'
down_revision: Union[str, Sequence[str], None] = '0004be5e009a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
